### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by aadilayub** [renerocksai/sublime_zk#101]
I'm getting the following error on creating a new Zettel:

![image](https://user-images.githubusercontent.com/31581044/78169330-a44bae00-746a-11ea-8e0e-4b87e455667c.png)

I am using Sublime Text version 3.2.2 with no plugins installed. 

The solutions mentioned in previous issues (#141) cannot be applied in my case as I have no plugins that could be causing the error.

**Comment by Derpius** [comment]
Did you install the package directly through package control or manually?

If you installed directly then the only thing I can suggest is using this (see attached) `.sublime-syntax` file that works for me (you'll have to rename it from `.txt` to `.sublime-syntax` as github only supports attaching basic file types)

If you installed it manually, you can still try replacing the syntax file as stated above, but I'd recommend deleting the broken package and reinstalling it using package control (you need to add this github repo to package control first though)
<hr>

If this answers your question please close the issue yourself by pressing the close issue button, as the developer of this plugin appears to be inactive (no commits since two years ago, no resolved issues since around the same time etc.)

[sublime_zk.txt](https://github.com/renerocksai/sublime_zk/files/4567337/sublime_zk.txt)

**Comment by aadilayub** [comment]
I ended up reinstalling from package control and the issue went away. Thanks @100PXSquared
