### ISSUE TITLE
Acceptable Characters for tags

### ISSUE THREAD

**Issue by cognociente** [renerocksai/sublime_zk#102]
Firstly, very excited to have found this package. I have been deep diving into Zettelkasten last few days and am a long-time Sublime fan - thank you.

I'm noticing that I cannot create tags like the following:
#!tag
#$tag
#%tag
#^tag
#*tag
#(tag

In all cases, it is the special character after the leading "#" that is causing the problem AND not allowing it to be recognized as a valid tag.

Is their a reason for this in terms of conflict with some other part of the sublime_zk package OR is this merely an artificial limitation?

====
 
Reason for my question is that I would like to use this single character to denote the "tag collection" to which this particular tag belongs. This allows for a natural grouping of my tags when presented in alphabetical order.

My taxonomy:
$ = All Companies
& = All Interactions like meetings
Etc...

**Comment by Derpius** [comment]
A hash symbol and a special character after it are used as commands, e.g. `#!` gets all tags, asterisk is a wildcard so can't be used anywhere after a hash (unless you want a wildcard there, check the documentation).

The reason why the others don't work (I assume even if they don't have a command attached to them) is because the plugin parses anything after a escape character, like # or [. And in the case of the #, assumes that a symbol immediately after a #, is a command selector, not a tag name.
<hr>

If this answers your question please close the issue yourself by pressing the close issue button, as the developer of this plugin appears to be inactive (no commits since two years ago, no resolved issues since around the same time etc.)
