### ISSUE TITLE
Can't get the color scheme to change for Zettel 

### ISSUE THREAD

**Issue by parakayw** [renerocksai/sublime_zk#106]
Hey, 
I set up the sublime_zk correctly, but am having trouble getting it to switch to the Monokai Extended color scheme.  I placed "color_scheme": "Packages/sublime_zk/Monokai Extended-zk.tmTheme", in the command line of Sublime ZK user and default settings and it still has not change the scheme of a new zettel not. I am not a programmer and this is all very new to me. Any assistance will be welcome. I should also point out that I use Windows.

**Comment by aadilayub** [comment]
I'm experiencing the same problem. By default, all zettelkasten notes have syntax set to "Zettelkasten Saved Searches" and use this light colorscheme. Changing syntax to "Markdown Zettelkasten" switches them to the dark monokai scheme, but only temporarily.

![image](https://user-images.githubusercontent.com/31581044/81644818-e55bb880-9441-11ea-8b66-c99bb2836f3b.png)

**Comment by Derpius** [comment]
In the top bar with a markdown file open, go to:
View -> Syntax -> Open all with current extension as... -> sublime_zk (or whatever it calls itself in the list) -> Markdown Zettelkasten

Note: I can't check this myself at the moment as I've just switched to a new computer and don't have sublime_zk set up on it yet.
<hr>

If this answers your question please close the issue yourself by pressing the close issue button, as the developer of this plugin appears to be inactive (no commits since two years ago, no resolved issues since around the same time etc.)

**Comment by aadilayub** [comment]
Thanks @100PXSquared! Also, could you explain what the 'Zettelkasten Saved Search' syntax is? Would we be losing any functionality by replacing it with Markdown Extended Syntax?

**Comment by parakayw** [comment]
Thanks for your help!
