### ISSUE TITLE
plugin fails when used without project

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#11]
It appears the plugin requires the use of a project. When I use **File** > **Open Folder...** and open my notes folder (not a sublime project) and try to use the plugin I get this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 60, in run
    folder = os.path.dirname(self.view.window().project_file_name())
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

Project support is ideal, however some users might just want to open a folder in Sublime and do their work not bothering with projects. Are you open to removing the project-only requirement?

**Comment by renerocksai** [comment]
My rationale was this: 

* Usually you have a note archive. 
* To create new notes the path to the note archive must be known
* So usually you would configure the path to the note archive in the settings file
* But then you can only ever have one note archive, which is inflexible
* So projects to the rescue: If there's a project, there's a path
* Since the project defines the path: One can have multiple of them

I am open to removing the project requirement, sure. If there is a sane way to ensure no unexpected behaviour.

Let's assume one of the two is true:

* a view / file is open that is part of the note archive 
* a project file is open

Then the path to the archive is known.

This is the case when following a link or creating a link from within the view.

What to do when none of the above is true (File->New Window) ? 

Options: 
* Have a default path in the settings where new notes are created
* Show some sort of save-as dialog
* Quietly ignore the NewZettelCommand and document this behaviour in README.md

?

**Comment by renerocksai** [comment]
I got it worked out: It all works as you suggested in your pull request when we have an open file. So only NewZettelCommand is the problem when we have a new window. In that case I am going to invoke `save_project_as` :). Escaping out of that will cause the new note creation to fail :-)

**Comment by toolboxen** [comment]
> Show some sort of save-as dialog

Yes! this is what I was going to suggest. throw an message to the user when trying to create a new note without a known path. Your solution of `save_project_as` is perfect because someone making a new note in a new window is likely just starting a new zettelkasten, so encouraging them to create a Sublime project for the new zettelkasten is the ideal method here. Good solution!
