### ISSUE TITLE
search index api

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#19]
Our discussion on #18 reminded me:

Sublime Text indexes the entire contents of any opened folder, or any project folder. It stores this index and queries against it for the GoToAnything functionality. It is quite fast, and it might be useful for plugin developers to be able to query that index.

- For example, you wouldn't have to scan the folder contents, you'd simply query the **already existing index** and return the list of files that match to your requirements.
- Better yet, since the index also includes the **entire contents of every file** you could query against the note titles inside each note to match them to the file names, and run a background worker process to update the note filenames if a note title is changed... and vice versa.
- Even better yet, you could query the index for a list of files containing tags `#tag1` and open a new tab containing a list of all notes tagged with `#tag1`, some stats on the number of files, also displaying the note title and the zettel link for users to quickly navigate the tags they set within the files.

But as of yet there is no API for the search indexing. so all this useful functionality must be duplicated in much slower python code.

I closed this issue since no action is required, it's just an observation. 😄

**Comment by renerocksai** [comment]
Well, I explicitly inhibit word completions via `sublime.INHIBIT_WORD_COMPLETIONS` to force SublimeText to ignore other suggestions than my own. I find this useful because we use it for link creation. So once you find something it better be a note because it will get brackets around it.

Of course it could be checked whether a file exists -> make a link or else it was just a word completion.

For your 3rd point: find in files is a good start here. No statistics but it opens a new window/tab containing matching files, clickable, with context.

2nd point - I would be wary about file system changes under the hood. It's entirely doable. But I would do it less automatic. Maybe: Check in the background if a title in a view does not match its filename. Highlight it in some way, maybe with a gutter symbol, and have a shortcut (or something) that lets you fix the file name and another one that lets you fix the title.

Another idea I had was a command creating a new tab with a sorted list of all existing #tags in the project, fuzzy-searchable. Maybe an overlay. This is useful when you're not sure if you have a specific tag already or you're not sure whether you already have used a synonymous tag... Binding it to '#' would be silly though, with all the headings :)

**Comment by renerocksai** [comment]
Maybe bind the tag selector (why not?) to '#'+'.' or '#' + '?'

**Comment by toolboxen** [comment]
> For your 3rd point: find in files is a good start here.

True! Although you cannot open multiple find-in-files and it would be
great to have multiple tag-lists open at once.

Prompting the user for note title changes is indeed a better option.

> Another idea I had was a command creating a new tab with a sorted list of
> all existing #tags in the project, fuzzy-searchable.

Great idea. I built something similar for Atom, I generated the tag list
and shoved it into a new tab, so the list was always visible until the
user closed it. I had all the tags using `@` symbol and a special tag
with `@alltags` -- these were actually links to run a grep (faster than
python) so that clicking `@alltags` opened a new tab with a grepped list
of all tags in all files. While clicking a `@tag` tag would just show
only files with that tag. The list of files were clickable as well.

**Comment by renerocksai** [comment]
Wow, great feature! I am just contemplating populating a tag list (with '#' as tag prefix but could be configurable). I would love to but don't want to rely on grep since it's not available on windows I suppose, must be in the path or configured -- a bit of a pain.

Somehow showing a list of all files containing a specific tag sounds very useful. I wonder how that could be done in sublime.

**Comment by toolboxen** [comment]
There is some limited access to the search index with symbols. If you
have defined symbols then you can access those using GoToAnything but I
think you can also access them programmatically as well:
http://docs.sublimetext.info/en/latest/reference/symbols.html

So perhaps `#string` or `@string` could be defined as symbols, then
sublime would index them and you could build from there?

> Somehow showing a list of all files containing a specific tag sounds very
> useful. I wonder how that could be done in sublime.

You can populate a new tab or even a new split with any kind of content,
so getting that list generated is your only hurdle ;) Maybe take some
inspiration from MarkdownLivePreview?
https://packagecontrol.io/packages/MarkdownLivePreview

**Comment by renerocksai** [comment]
I am currently experimenting doing an overlay and searching the probably super-bad python way. Thanks for your pointers. I think I can get a tag list (even if it's slow at first -- must check out symbols) but I have no idea how to go about the tabs & stuff. MDLivePreview is probably worth checking out. Making stuff clickable would be the next step

**Comment by renerocksai** [comment]
Haha if you pull now, the experimental tag selector (overlay) is in :) shortcut is `#?`.

eventhough it is pure python and probably not the most efficient, it's not that slow. but then again I have less than 100 notes.

**Comment by renerocksai** [comment]
![sublime_tags1](https://user-images.githubusercontent.com/30892199/32405205-25f94bc0-c161-11e7-914a-1a82bdf9c2f9.png)

**Comment by renerocksai** [comment]
hmmm. MarkdownLivePreview looks interesting. However, it creates an HTML view. That probably doesn't lend itself to showing clickable tags. As the HTML viewer of SublimeText would try to follow hyperlinks... But I could be totally wrong here. Must check out Sublime's API to see what window options there are.

**Comment by renerocksai** [comment]
the more I think about tags, the more I think

* text files and tags -> sophisticated tag (combination) searches in files are best left to the editor.
    * Having a simple command that can take a selected tag and run find-in-files would be the furthest I would go, probably
* leaves us with producing a fuzzy-searchable tag list, useful for checking what tags there are and quickly inserting them
    * this is where the index comes into play
* and optionally a command that just produces a text window containing all tags because the overlay is somewhat limited

**Comment by toolboxen** [comment]
> Haha if you pull now, the experimental tag selector (overlay) is in :) shortcut is #?

Nice! works for me. Perhaps register a command with the Command Palette to allow people to run `ctrl+shift+p/cmd+shift+p` > **Sublime ZK: Show All Tags** and get the overlay that way.

> Having a simple command that can take a selected tag and run find-in-files would be the furthest I would go, probably

That makes sense. And is simple enough, get word/selection and send to `find_in_files`

> I think I can get a tag list (even if it's slow at first -- must check out symbols) but I have no idea how to go about the tabs & stuff
>optionally a command that just produces a text window containing all tags because the overlay is somewhat limited

the `sublime.View` class offers an `insert(edit, point, string)` method where you can populate a new view with some content: https://www.sublimetext.com/docs/3/api_reference.html#sublime.View so you can open a new view, fill with content, and then set the syntax of that view to Markdown Zettel to have it properly highlighted.

**Comment by renerocksai** [comment]
>Perhaps register a command with the Command Palette to allow people to run ctrl+shift+p/cmd+shift+p > Sublime ZK: Show All Tags and get the overlay that way.

I am a bit wary here. This command would only work (or at least be intended) for note archives, so it's very specific to this package. An application command... Hmmm... Would require a code change. Currently it's a TextCommand so it is triggered right in the view. But that's not really the issue. I was more thinking that it's a bit clumsy to have to invoke the command palette.

> the sublime.View class offers an insert(edit, point, string) method where you can populate a new view with some content: https://www.sublimetext.com/docs/3/api_reference.html#sublime.View so you can open a new view, fill with content, and then set the syntax of that view to Markdown Zettel to have it properly highlighted. Just to clarify this is would just be an unsaved tab and not actually a file.

Thanks for the hint. I did it almost like you suggested. The problem here was that `edit` objects cannot be created by oneself (anymore). They are provided by `TextCommand`s. So I used the alternative to `run_command("insert, ...` to insert the text. 

This is what it looks like, it's triggered by `[#][!]`:

<img width="1112" alt="sublime_zk_tags" src="https://user-images.githubusercontent.com/30892199/32414889-2792394a-c230-11e7-98ce-a8d8dd665a39.png">

**Comment by renerocksai** [comment]
> That makes sense. And is simple enough, get word/selection and send to find_in_files

Turns out, that's not simple at all to do from a plugin. The only way to trigger find-in-files is to run the `show_panel` command, requesting it to show `"panel": "find_in_files"`. The **only** field that cannot be set is the search-string!

:) I got around that by selecting the tag, calling `copy`, calling `show_panel`, and then `paste` :)

So now you can, just as with note-links, put the cursor into a #tag and press [ctrl]+[enter]:

<img width="971" alt="sublime_zk_tag_search" src="https://user-images.githubusercontent.com/30892199/32421934-1e1411f0-c29d-11e7-8e08-7f7775e32542.png">

Then press [enter]:
<img width="971" alt="sublime_zk_tags_results" src="https://user-images.githubusercontent.com/30892199/32421958-52a9cdec-c29d-11e7-9240-1a229a82351e.png">

Which makes searching for notes containing a (single) tag quite quick:

* click
* [ctrl]+[enter]
* [enter]

:)

**Comment by toolboxen** [comment]
> I am a bit wary here. This command would only work (or at least be intended) for note archives, so it's very specific to this package. 

Right, the commands are only available when the plugin is active.

> I was more thinking that it's a bit clumsy to have to invoke the command palette.

Many plugins register all their commands to the Command Palette so that users can easily run the commands in the event that their keybinds have been messed up (which can happen quite often with new users) -- The Command Palette provides a secondary way to trigger the commands, the keybinds are the primary way.

> This is what it looks like, it's triggered by [#][!]:

Looks good!!

> Turns out, that's not simple at all to do from a plugin. The only way to trigger find-in-files is to run the show_panel command, requesting it to show "panel": "find_in_files". The only field that cannot be set is the search-string!

Ahhh, right! You can get the current word/selection and use it to autofill the `show_overlay` but not the `show_panel`... that's oddly inconsistent... :thinking: I just assumed panels would have a consistentcy with overlays.

At least you got it to work with the copy/paste!
