### ISSUE TITLE
"<" trigger link menu

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#21]
Hi, 

![image](https://user-images.githubusercontent.com/183266/32783937-af9a8530-c94d-11e7-96b4-e60b6428274d.png)

after typing < the menu with all available Zettels are appearing, nothing happens if I type [

**Comment by renerocksai** [comment]
Hi,

I noticed the < on Linux today, too. Probably some default trigger in
sublime. Can check it later this evening.

Have you tried [[ instead of [   ?

The key binding to bring up the overlay is set to [[ no matter if double
bracket link style is selected or not. The latter only applies to the
inserted link.

Rene



Am 14.11.2017 15:10 schrieb "wangeleile" <notifications@github.com>:

Hi,

[image: image]
<https://user-images.githubusercontent.com/183266/32783937-af9a8530-c94d-11e7-96b4-e60b6428274d.png>

after typing < the menu with all available Zettels are appearing, nothing
happens if I type [

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/renerocksai/sublime_zk/issues/21>, or mute the thread

**Comment by wangeleile** [comment]
Hab ich, äh I have tried both

I am working on windows.

**Comment by renerocksai** [comment]
Aaaah, OK, ich hab grad nur macOS und Linux, bin auf Konferenz. Aber das OS
sollte nicht das Problem sein, ausser ich hab in der Windows keymap einen
Fehler.

Schnell hintereinander [[ geht eigentlich immer.

Wenn du mit Ctrl + ` die Konsole öffnest und dann im Text [[ machst, kommt
dann ein Fehler in der Konsole?



Am 14.11.2017 15:18 schrieb "wangeleile" <notifications@github.com>:

**Comment by wangeleile** [comment]
Es passiert garnichts, in der Konsole taucht auch kein Fehler auf. Vielleicht ist das eine andere Keymap. Quasi wie das z und y bei englischen Tastaturen.

**Comment by renerocksai** [comment]
Hmmm, [[ ist schon so lange im Plugin, das ist so robust wie's mir geht.
Kann es sein, dass du

* Kein Projekt hast
* Ein Projekt, das in einem anderen Verzeichnis liegt als deine .md Files
* Mit Unterverzeichnissen arbeitest, sodass das Plugin nicht einfach den
Pfad zu deinem Archiv bestimmen kann?

Das Plugin versucht erst als Archiv-Verzeichnis das des aktuellen Projekts
zu nehmen. Gibt es kein Projekt, wird der Pfad des aktuellen Dokuments
genommen.

Wenn [[ unverrichteter Dinge gleich wieder aufgibt, kann es wohl den Pfad
ins Archiv nicht finden und daher auch nicht die dort vorhandenen Files
listen, ...

Sobald ich wieder Zugriff habe (im ICE), Guck ich mal, ob sich ein Fehler
in die Windows keymap eingeschlichen hat



Am 14.11.2017 18:49 schrieb "wangeleile" <notifications@github.com>:

**Comment by renerocksai** [comment]
Hab gerade gepusht. Die aktuelle Version schreibt in die Konsole, wenn es
den Pfad nicht finden kann. In dem Fall am besten ein Projekt anlegen siehe
readme.

Um zu sehen, ob [[ bei dir erkannt wird, kannst du in der Sublime-Konsole
folgendes Kommando ausfuehren:

sublime.log_commands(True)

Dann im Text [[ eingeben, das sollte in der Console

command: get_wiki_link

erzeugen. Wenn nicht, dann stimmt wirklich was mit Deiner Keymap nicht,
denke ich.



Am 14.11.2017 18:49 schrieb "wangeleile" <notifications@github.com>:

**Comment by renerocksai** [comment]
Hab gerade gepusht. Die aktuelle Version schreibt in die Konsole, wenn es
den Pfad nicht finden kann. In dem Fall am besten ein Projekt anlegen siehe
readme.

Um zu sehen, ob [[ bei dir erkannt wird, kannst du in der Sublime-Konsole
folgendes Kommando ausfuehren:

sublime.log_commands(True)

Dann im Text [[ eingeben, das sollte in der Console

command: get_wiki_link

erzeugen. Wenn nicht, dann stimmt wirklich was mit Deiner Keymap nicht,
denke ich.


2017-11-14 18:48 GMT+01:00 wangeleile <notifications@github.com>:

**Comment by renerocksai** [comment]
Two more things:

From the Sublime Text docs:
> Auto complete shows the completion popup as you type, so you can fill in long words by typing only a few characters. It's enabled by default for source code and HTML (but only after entering a < character).

So `<` seems to be Sublime's preferred auto-complete key. So it's configuration dependent: on my mac it's `[ctrl]+[space]`.

I am wondering: when auto-complete works for you, then `[[` **must** work, too. I don't see a way where it wouldn't. Can you verify that the `get_wiki_link` command is executed when you press `[[`? (see German note above how to enable logging)

**Comment by renerocksai** [comment]
Being super paranoid I just comitted a patch that renames all commands that don't already start with zk_ to start with zk_ now.

This is to make avoid command name clashes with Dan Sheffler's MyWiki package. This is the last thing I can think of that causes your `[[` to not work.

**Comment by wangeleile** [comment]
When I type [[ log shows this
command: insert_snippet {"contents": "[$0]"}

**Comment by renerocksai** [comment]
ah, that is interesting: so your sublime seems to be configured with some snippet. that seems to take precedence and shadows the plugin command :-| 

http://sublimetext.info/docs/en/extensibility/snippets.html has more info on snippets. 

You might try to disable your snippet (probably somewhere located in your Packages/User folder) or change the plugin's key bindings:

Preferences->Package Settings->sublime_zk->Key Bindings (User)

And insert a line like this:
```
    { "keys": ["alt+["], "command": "zk_get_wiki_link"},
```
but make sure the line before ends with a , coma if it's a key binding line

That maps `[alt] + [[]` to pop up the notes list.

Attention: Only do this with the most current version, because I have renamed the commands.

If you haven't refreshed, then just replace `zk_get_wiki_link` by `get_wiki_link`

Hope that helps.

**Comment by renerocksai** [comment]
I sum up:

* `<` triggers auto-completion in your SublimeText config. Also in my Linux config. We might want to change that in our Sublime Configs to `[ctrl]+[space]`. Not a problem of the plugin, though.
* `[[` is already occupied by a snippet in your SublimeText config and you can add an additional key mapping if you want to keep the `[[` snippet.

So I'm going to close this now.

Thanks for your patience :)

**Comment by wangeleile** [comment]
I found the problem. 
It has nothing to do with the snippets. Sublime has in general problems with keybindings. 
[look here](https://github.com/SublimeTextIssues/Core/issues/392)

So, maybe to avoid for non-englisch people, whe should like you suggest, defining key bindings by default.

**Comment by renerocksai** [comment]
Very odd. I was not aware of that. But `insert_snippet` looks suspiciously like snippet stuff :wink: 

I suppose I can put in a few more key bindings for windows, but it's a bit hard for me to test at the moment.

do you know of other keys that are referenced in the README that work differently?

I would rather add Windows specific key bindings than change them, especially for `[[`. This is just the way it should work. Changing it for everybody (mac and linux users) just because of Sublime Windows doesn't feel right.

I know of one Zettelkasten.de forum user, toolboxen, who uses Windows, too. He never mentioned [[ not working. I will ask him.

**Comment by toolboxen** [comment]
https://forum.zettelkasten.de/discussion/comment/429/#Comment_429

**Comment by renerocksai** [comment]
I just checked: The `<` trigger is actually in SublimeText's default config:

```
// Additional situations to trigger auto complete
    "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ],
```

If you go to Preferences --> Settings, you can see it in the left (default) pane when you search for "complete". You might want to change this if it annoys you.

**Comment by renerocksai** [comment]
Also, see https://github.com/SublimeTextIssues/Core/issues/1251 for why ctrl+space does not work on Linux: It was a choice:

> wbond commented on Jun 28, 2016
> This key binding was changed with build 2183, over 4 years ago. The default was changed because ctrl+space is used by IMEs.
>
> I'm doing to close this as wontfix, since it was an intentional change.

> FichteFoll commented on Jun 29, 2016
> This is indeed one of the few default key bindings that are different between Linux and Windows (and has been for a long time).

**Comment by toolboxen** [comment]
Here's default `<` on Windows:

![123](https://user-images.githubusercontent.com/33474961/32827271-72441a86-c9a0-11e7-84c8-0705b2985377.gif)

**Comment by toolboxen** [comment]
So to clarify: default `<` functionality on Windows is:

1. typing `<`: no response
2. typing `<` then space: no response
3. typing `<` then tab: no response
4. typing `<` then character: trigger HTML tag autocomplete popup

After installing plugin:

1. typing `<`: trigger filename autocomplete popup

**Comment by renerocksai** [comment]
You are working in **Plain Text**!

Does the Text have the scope `text.html` or a child scope? If so, then completion is triggered just by pressing `<` -- but the plugin in charge handling the completion rather waits for at least 1 more character.

Our plugin is meant as a quick way to insert a note link. So waiting for a `2` (current millenium) would be a bit odd.

**Comment by toolboxen** [comment]
After installing plugin, `<` changes

![123](https://user-images.githubusercontent.com/33474961/32828098-14a24864-c9a3-11e7-8479-3ef1f12d9828.gif)

**Comment by toolboxen** [comment]
> You are working in Plain Text!

No you'll see I start with markdown then choose Plain Text to show difference.

**Comment by renerocksai** [comment]
```
 "auto_complete_triggers": [ {
"selector": "text.html", 
"characters": "<"
} ],
```
Reads: 
* autocomplete
* in HTML scope
* when < is pressed

The plugin autocompletes. Because Markdown is `text.html.markdown`

**Comment by toolboxen** [comment]
> Does the Text have the scope text.html or a child scope? If so, then completion is triggered just by pressing < -- but the plugin in charge handling the completion rather waits for at least 1 more character.

In Markdown and in Plain Text both, the `<` waits for at least one more character. Just typing `<` should do nothing.

**Comment by renerocksai** [comment]
>> You are working in Plain Text!
> No you'll see I start with markdown then choose Plain Text to show difference.

:smile: yeah I see :smile:

I rest my case. You have a plugin that does regular Markdown / HTML completion.
It behaves like you are used to.
Now our plugin responds without further keypresses.

And after all I have researched so far, it probably always hast

**Comment by toolboxen** [comment]
Nope, no plugin! The first GIF is a vanilla Sublime Text install, no packages. Second GIF is 1 package installed: sublime_zk

**Comment by toolboxen** [comment]
I see what you mean about `auto_complete_triggers` it seems like the documentation is not explicit in exactly what's going on here...

**Comment by renerocksai** [comment]
I am pretty sure Windows and Linux behave the same way here. I can test later to disable my plugin. I think it just has to do with: you are used that your Markdown / HTML plugin waits for an extra character.

We want ctrl+space to work. So we need to trigger upon auto completion. Once we do, we get triggered by <.

**Comment by toolboxen** [comment]
Here it appears that ctrl+space is actually alt+/ on linux: http://docs.sublimetext.info/en/latest/extensibility/completions.html?highlight=complete#how-to-use-completions

> Completions can be inserted in two ways:
    through the completions list :
        Ctrl + Spacebar on Windows / OS X,
        Alt + / on Linux
    or by pressing Tab.

> you are used that your Markdown / HTML plugin waits for an extra character.

No, there is no plugin here, I've never used a Markdown plugin before, I am completely fine with using the default Markdown syntax of Sublime.

**Comment by toolboxen** [comment]
Another thing to think about: if you install another auto-completion package from packagecontrol.io and try typing `<` it will no trigger popups. Pressing `ctrl+space` or `alt+/` will.

**Comment by renerocksai** [comment]
But you can't argue away that the trigger is set to that < key for html scopes.
Just because sublime text waits for an extra character does not mean our plugin does something wrong. When it gets asked for completions, it provides completions.

Sorry when this messes up your completion list. And sorry that it works immediately. if we press ctrl+space we also want immediate completion, so at the moment I don't see a way to prevent this unless we can find out a difference between ctrl+space and < (or some other binding). OK, I am gonna try something.

The messed up completion list I think I can't fix. Either you want note link creation via auto-complete or not :)

But maybe I can get access to that < key and maybe there's a chance to suppress completion when there is a < in the text.

**Comment by renerocksai** [comment]
It will trigger. Believe me. If the scope is text.html, it **will**. But plugins can decide not to provide completions.

**Comment by toolboxen** [comment]
I understand now: triggering event vs triggering popup. User perspective vs. plugin developer perspective 😝

**Comment by renerocksai** [comment]
Exactly. Sorry for the confusion.

I just hacked together the fix and pushed it to master
