### ISSUE TITLE
Automatically include full citation from bibfile to the bottom of current zettel

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#25]
Well, this is a quite rough concept and I hope I explain it well. 
I work with zotero which generates automatically a bib file. For each citation I have a unique cite key. The file is in the same folder like all zettel.

I like to have the full citations in each zettel, because it is more secure and I am lazy. 

So, her the idea. 
1. Would it be possible, just to use the citekey somewhere in the text and with a shortcut, your addon will add at the end of the file, all cited sources in pandoc style. 
2. Would it be possible to have a function similar to STRG+SPACE, but for bib sources. 

So, the workflow would be. 
1. Include the citekey [@Fast2015] somewhere in the text. 
2. Press shortcut, all used citekeys will be added at the end.
e.g. [@Fast2015]:Fast, Sascha, und Christian Tietze. Die Zettelkastenmethode: Kontrolliere dein Wissen. CreateSpace Independent Publishing Platform, 2015.

**Comment by renerocksai** [comment]
Now, **this**, Mr. Wangeleile, is one of the best suggestions I have read in quite a while! I could see myself using this feature basically all the time! What a great input!!!

I can totally see how this could be done once the plugin understands citekeys -- citekeys are pretty robust, so searching for them would not cause false positives regardless of how you cite ([@citekey] or @citekey or [#citekey] or  ...). That's the easy part. I *guess* the hard part is getting the bibliography entries right (the longtext version, so to speak). In addition, people will probably want to style them to their liking:

Maybe somebody wants this format:

```
[#fast2015]: Fast, Tietze, 2015. "Die Zettelkastenmethode: Kontrolliere dein Wissen". 
             CreateSpace Independent Publishing Platform
```

I will dig into parsing .bib files. I am with you, first supporting pandoc style is the way to go.

Thanks a lot for bringing this up!!!

**Comment by wangeleile** [comment]
Well thank you,  ideas are my special power, coding not. Some of this concepts I hat earlier when I tried to build an addon like yours for visual studio code. But, i am so f.....ing slow in coding.

**Comment by renerocksai** [comment]
😄 always happy if I can help. I like your ideas. Well, SublimeText plugins are written in python, that's a big advantage imho. Everything's much easier in python 😄 

@citekey completion via ctrl+space is in now. You have to add a setting to your ... settings :)

```
    // for auto-completion of citekeys and auto-bibs
    // enter the full path to your .bib file here
    "bibfile": "/path/to/zotero.bib",
```
If you press ctrl+space, the @citekeys will be at the end of the suggestion list, so you have to scroll down to see them or just start typing "fast" (for fast2015) and you will see. Just *never*, *ever* use the `@` key. For some reason this causes (my) SublimeText to just insert the current suggestion (which always is a zettel note) instead of filtering the completions list to show suggestions that start with `@`.

The citekey will be inserted it `[@citekey]` format :)

For the other stuff (the automatic bibliographies at the end of the note) I better call pandoc directly. that will take a bit of work.

**Comment by wangeleile** [comment]
:+1:

**Comment by renerocksai** [comment]
if you like, you can try it out: the command in the command palette is called `ZK: Auto-Bib`

Just be careful, please: Everything after the marker line will be replaced. So pls don't put text under the auto-generated references.

**Comment by renerocksai** [comment]
😃 
![autobib](https://user-images.githubusercontent.com/30892199/33104798-659550d6-cf2a-11e7-8a96-4c9de34d7770.gif)

**Comment by renerocksai** [comment]
bigger...
![autobib](https://user-images.githubusercontent.com/30892199/33105451-6851a402-cf2d-11e7-8b5a-3d869a269aa0.gif)
