### ISSUE TITLE
Cascading .bib files load order

### ISSUE THREAD

**Issue by DivineDominion** [renerocksai/sublime_zk#26]
Noticed the new `["bibfile": "/path/to/zotero.bib"]` setting. Here's a suggestion to add a contextual setting.

Since some crazy people seem to use multiple note archives, some of these will be using per-project Zettelkästen. That means they create a new folder for every major project, possibly including a research database. So instead of using 1 central `.bib` file only, I suggest to allow `.bib` files on a per-project/per-folder basis.

Imagined load order:

1. Preferred `.bib` filename to look for in the current directory (since people seldomy use more than 1 file, this might be superfluos if you implement (2))
2. Find and use _any_ `.bib` file in the current directory
3. Use one single centralized `.bib` file

**Comment by renerocksai** [comment]
Very good suggestion, indeed. I was contemplating something similar. I like the *auto discovery* of `.bib` file approach. I would opt for:

1. *skipped* :smile: 
2. Find and use *any* `.bib` file in the current directory (note archive directory) ; search not descending into sub-folders
3. Use the single, centralized `.bib` file specified in the settings. 

Speaking about *cascading*: Technically it would be possible to use both the central **and** the local `.bib` file. Entries would be merged and local would override central. That way you could have your central default `.bib` and project specific material in a local `.bib`. But since this makes it more complicated and is bound to be a source of confusion, I am staying away from merging `.bib`s for now.

Thanks a lot for the really good suggestion!

**Comment by renerocksai** [comment]
Done! 😄 

First the current directory is searched for a `.bib` and if nothing's there, then the settings will be queried.
