### ISSUE TITLE
Alt+enter returns no results (using ag in Win10 PowerShell)

### ISSUE THREAD

**Issue by berdan** [renerocksai/sublime_zk#32]
I have notes linking to eachother, but alt-enter gives me no results. Tried setting Verbose to true in ExternalSearch run and the console gave me:

`
cmd: ag --nocolor -l --silent --markdown (\[201712292107)|(§201712292107) C:\Users\danie\Dropbox\00 - ZK
`

I'm using ag in PowerShell in Win10...

> PS C:\Users\danie> ag --version
>ag version 2.1.0
>
>Features:
>  +jit +lzma +zlib

...and there seems to be two problems with this; bad regexp and no handling of file paths with spaces. 

> PS C:\Users\danie> ag --nocolor -l --silent --markdown (\[201712292107)|(201712292107) C:\Users\danie\Dropbox\00 - ZK
> At line:1 char:54
> + ... ocolor -l --silent --markdown (\[201712292107)|(201712292107) C:\User ...
> +                                                    ~~~~~~~~~~~~~~
> Expressions are only allowed as the first element of a pipeline.
> At line:1 char:69
> + ... rkdown (\[201712292107)|(201712292107) C:\Users\danie\Dropbox\00 - ZK
> +                                            ~~~~~~~~~~~~~~~~~~~~~~~~~
> Unexpected token 'C:\Users\danie\Dropbox\00' in expression or statement.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : ExpressionsMustBeFirstInPipeline

If I surround the regexp and the path with single quotes, I get data that looks right (except bad character handling of the letter ö):
> PS C:\Users\danie> ag --nocolor -l --silent --markdown '(\[201712292107)|(§201712292107)' 'C:\Users\danie\Dropbox\00 - ZK'
> C:\Users\danie\Dropbox\00 - ZK/201712292101 Forum.md
> C:\Users\danie\Dropbox\00 - ZK/201712292139 M÷ten.md

**Comment by renerocksai** [comment]
Hi, I'll grab my Win10 laptop tomorrow and check what can be done here. Obviously the space in your archive path seems to be causing this (in part).

As for *bad regexp* and *no handling of file paths with spaces*: correct, this is a problem when you work in a (power) shell: the `|` in the regexp will be interpreted as a pipe operator by the shell and it has no chance of knowing where one argument ends and the next one begins if there are spaces.

When passing arguments (as a list / struct) to a process programmatically, this *usually* is not an issue; no shell involved that needs to parse arguments from the command line in order to pass them on to the new process. However, on Windows, there might be an issue. I'll check it and let you know...

**Comment by renerocksai** [comment]
From the [documentation](https://docs.python.org/3.3/library/subprocess.html):

On **Windows**, if _args_ is a sequence, it will be converted to a string in a manner described in _Converting an argument sequence to a string on **Windows**_. This is because the underlying `CreateProcess()` operates on strings.

## 17.5.6.1. Converting an argument sequence to a string on Windows

On Windows, an _args_ sequence is converted to a string that can be parsed using the following rules (which correspond to the rules used by the MS C runtime):

1. Arguments are delimited by white space, which is either a space or a tab.
2. A string surrounded by double quotation marks is interpreted as a single argument, regardless of white space contained within. A quoted string can be embedded in an argument.
3. A double quotation mark preceded by a backslash is interpreted as a literal double quotation mark.
4. Backslashes are interpreted literally, unless they immediately precede a double quotation mark.
5. If backslashes immediately precede a double quotation mark, every pair of backslashes is interpreted as a literal backslash. If the number of backslashes is odd, the last backslash escapes the next double quotation mark as described in rule 3.

==> To make it work on Windows, where the argument list is converted from list to string, arguments must be escaped in `""double quotation marks""`. This should be easy enough to do.

Thanks for bringing this up. Might catch us elsewhere, too...

**Comment by renerocksai** [comment]
Very interesting...

Apparently it had nothing to do with quoting or spaces. For some reason, when only searching for files, the file names are not captured from ag's output. They show in a console window. But are not returned via the stdout pipe of the subprocess. When adding the '--stats' parameter, only the stats get returned, showing, for instance, that there was 1 match, but not the matching file itself. When searching for #tags where not filenames but actual file contents are searched for, there is no issue. Very weird. Passing in '--ackmate', to make ag output in ackmate parseable format, did the trick. 

Please check on your end if this fixes it, then I am going to close this issue.

**Comment by berdan** [comment]
Yep, this did the trick. Thanks!
