### ISSUE TITLE
Change scope of searches

### ISSUE THREAD

**Issue by achamess** [renerocksai/sublime_zk#37]
Hi. I have subdirectories in my ZK. I'm wondering if it's possible to modify the search scope for 
- ZK note insertion [[search_for_note]]
- Tag searches and jump-to

**Comment by renerocksai** [comment]
While certainly doable, I fear it might break some things in the process, so heavy testing is required. It's next on my list.

**Comment by achamess** [comment]
Thanks! Already the package is extremely useful. This would just take it to the next level for me and others too. Do you use subdirectories?

**Comment by renerocksai** [comment]
Thank you! 😄 I didn't use sub-directories because the plugin didn't support it. No, really, I just used subfolders for media (images). Since I create all my notes with `[shift]+[enter]` they all end up in the root dir, which I never minded. Maybe in the future I'll manually organize my notes a bit more 😄 or even use scripts to create them in subfolders... One never knows.

Anyway, erm, it was surprisingly painless to enable subfolder support. I might have overlooked the one or other side-effect this has, but I'd close this issue for now... 

Happy subfoldering 😄!

**Comment by renerocksai** [comment]
btw i fixed this 
![image](https://user-images.githubusercontent.com/30892199/35772029-499633fe-0937-11e8-9ccf-078708c5716c.png)

**Comment by achamess** [comment]
That's great. I just updated. If i have a note in my main dir that has the fancy form :) it finds it now and inserts the title.

Does the subdirectory search work? I tried searching using `[[` and it still didn't recognize. Maybe the problem is the depth of my subdirectories?

The notes I'm searching for are two folders deep from the `root` `Sublime Zettel`

![screen shot 2018-02-03 at 5 17 30 pm](https://user-images.githubusercontent.com/7445362/35772079-3ab4ca20-0906-11e8-9379-d29752d5213d.png)

**Comment by renerocksai** [comment]
the subdir search is supposed to work now, too. Yet I tested it only with 1 levels deep. ag shouldn't care about the number of subdirs. maybe it's something subtle in the code. I will test it using your screenshot

**Comment by renerocksai** [comment]
This is odd. It works here:
![image](https://user-images.githubusercontent.com/30892199/35772232-982ea9c6-093a-11e8-81c7-c9d501006700.png)

And is Sublime_Zettel your root folder? Did you (auto-) create a project there? I wonder what's different in your setup.

**Comment by achamess** [comment]
Everything works now! Maybe it just took a while. This is amazing! Thank you. The bib search is extremely powerful. And now I can go into the subdirectories. Wow.

**Comment by renerocksai** [comment]
Yayyyy 😄 
Glad it works now and glad you're happy  😄

**Comment by achamess** [comment]
Hi again. So from a note in my main directory `/Sublime_Zettel` I can do `[[` and find notes in my subdirectories. But from a note in a subdirectory, I can't search outside of that directory. Only the notes in the directory show up.

**Comment by renerocksai** [comment]
OK, got ya! In most cases the plugin first checks if there is a project directory and falls back to the folder of the current note. This doesn't happen on `[[`. I'll fix that and search for other places where this might impact working with subdirectories.
Thanks for pointing this out! Will let you know when it's done.

**Comment by renerocksai** [comment]
Actually, hang on: Before changing anything I tested what you described. In my test archive with subfolders, including the example you provided via screenshot earlier, I get all notes to show up on `[[`, even the ones in the parent folders of sub/subsub-folder notes. Is it possible that you don't have a project file? See [Creating a project](https://github.com/renerocksai/sublime_zk#manual-approach).
?

**Comment by renerocksai** [comment]
In addition, I just checked: my previous comment regarding checking for project folder when pressing `[[` was wrong: It is done there, too. So as long as you define a project as described in the [README](https://github.com/renerocksai/sublime_zk#manual-approach) it should work.

**Comment by achamess** [comment]
![screen shot 2018-02-07 at 8 03 13 am](https://user-images.githubusercontent.com/7445362/35917822-8398b330-0bdd-11e8-867c-ffbbe04f1cec.png)

Here I am inside a note that is in one of my subdirectories, and I'm searching for a note `Taxonomy of notes` that is in the main directory `/Sublime_Zettel`.

Here is a screenshot of the project that lives in that main directory:
![screen shot 2018-02-07 at 8 05 01 am](https://user-images.githubusercontent.com/7445362/35917852-a5fce98c-0bdd-11e8-885b-2bf1844eb4f1.png)

Not sure what's going on.

**Comment by renerocksai** [comment]
Hi,

I am speculating here. Did you open the project? At the moment the only
reason for that behavior I can think of is if there is a project file but
it was not opened via project open / recent project...?



Am 07.02.2018 14:06 schrieb "achamess" <notifications@github.com>:

[image: screen shot 2018-02-07 at 8 03 13 am]
<https://user-images.githubusercontent.com/7445362/35917822-8398b330-0bdd-11e8-867c-ffbbe04f1cec.png>

Here I am inside a note that is in one of my subdirectories, and I'm
searching for a note Taxonomy of notes that is in the main directory
/Sublime_Zettel.

Here is a screenshot of the project that lives in that main directory:
[image: screen shot 2018-02-07 at 8 05 01 am]
<https://user-images.githubusercontent.com/7445362/35917852-a5fce98c-0bdd-11e8-885b-2bf1844eb4f1.png>

Not sure what's going on.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/renerocksai/sublime_zk/issues/37#issuecomment-363762864>,
or mute the thread

**Comment by achamess** [comment]
Good call. My project file was corrupt or something, because every time I tried to switch to it, ST3 would abruptly crash (the window would try to open for 1s, but then close). So I deleted the project file and made a new one. Now I can search everywhere. Not sure what the problem was. Thanks!

**Comment by renerocksai** [comment]
Phew, glad you worked it out and it works now, I was beginning to run out
of ideas 😀

Happy zetteling 😀

Am 07.02.2018 14:18 schrieb "achamess" <notifications@github.com>:
