### ISSUE TITLE
ag search does not work when choosing a non-standard `wiki_extension`

### ISSUE THREAD

**Issue by merlinthered** [renerocksai/sublime_zk#39]
When you choose an extension that is not one of `.markdown`, `.mdown`, `.mdwn`, `.mkdn`, `.mkd`, or `.md`, searching with `ag` will not work, because it uses the `--markdown` command line option that limits the search to files with these extensions. I was trying to use an extension like `.zk` to make it easier to use the `sublime_zk` syntax only on zettelkasten files, but this broke the search. Maybe there is another way to make `ag` search only in specific files?

**Comment by renerocksai** [comment]
Hmmm, I'll check. Since we have a setting for filename extension, it would be only consistent to later find files with that extension 😄 . I can vaguely remember that trying to pass the filename extension to ag directly caused troubles -- but I'll look into it again. Maybe it can be fixed this time. New attempt, new luck 😄

**Comment by renerocksai** [comment]
New luck indeed: It's fixed!
I haven't tested it with `.zk` but with `.md` but provided `--markdown` is gone I am confident it will work with `.zk`, too
