### ISSUE TITLE
Unexpected syntax style formatting for MultiMarkdown Auto-Bib

### ISSUE THREAD

**Issue by heychad** [renerocksai/sublime_zk#40]
I think there may be some odd syntax style formatting going on with MultiMarkdown citations when I use an external .bib file and the ZK_Auto-Bib function. I have not highlighted any of the text, that pink is its default. And it's strange that it only happens after the comma in the name...

<img width="580" alt="screenshot 2018-02-13 13 55 59" src="https://user-images.githubusercontent.com/2905788/36174307-fac6c40a-10d9-11e8-997a-01839dec7b52.png">

When I used the default Pandoc format everything looked normal, same as your Readme screenshots. Hope this helps to troubleshoot!

**Comment by renerocksai** [comment]
Hi, I encountered this, too but can't remember what I did to get rid of the highlighting. The highlighting basically shows you illegal characters according to the syntax. It seems that multimarkdown syntax for `[key]: value` only allows for values without spaces, probably because it is meant for URLs.
I have added a special case for our special `[#citekey]: full citation` style references to the plugin's syntax file. The highlighting should disappear when you next update the plugin. Maybe give it a few minutes time, though. Another user observed that his update seemingly didn't go through when he updated a minute after I had pushed...

Thanks for all the info, this really helped troubleshooting! 👍
