### ISSUE TITLE
Auto-Bib: Extra Sources

### ISSUE THREAD

**Issue by doctornerdis** [renerocksai/sublime_zk#47]
Hi again, 

Sometimes when I use the `Auto-Bib` feature (which I love, BTW), I end up with additional sources that aren't cited in the note. Here's a video: https://v.usetapes.com/Y4HNPx4HEc. Here, I have three sources in the text, but I end up with an extra two in the auto-generated references. 

What do you think?

**Comment by renerocksai** [comment]
There we go, you found something 😂!
I am away from my computer but will look into it soon. What comes to mind
is: autobib searches for citekeys and does not care whether they are in
brackets, whether they're prefixed with @, etc. So maybe some of your notes
contain constructs that contain or resemble citekeys from the bibfile.

Will know more after watching the video. I can easily change checking for
brackets / prefix btw. If that fixes it, it would be an easy win.

Am 20.02.2018 19:51 schrieb "doctornerdis" <notifications@github.com>:

Hi again,

Sometimes when I use the Auto-Bib feature (which I love, BTW), I end up
with additional sources that aren't cited in the note. Here's a video:
https://v.usetapes.com/Y4HNPx4HEc. Here, I have three sources in the text,
but I end up with an extra two in the auto-generated references.

What do you think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/renerocksai/sublime_zk/issues/47>, or mute the thread

**Comment by renerocksai** [comment]
Haha, I never thought this was going to happen 😄 . It's obvious, isn't it?

Thanks a lot for the video, it explains everything.

* `es_` is contained in #united_stat**es_**of_america
* `ted_` is contained in #uni**ted_**states_of_america

As I described before, Autobib works with the assumption that citekeys are unique and would never occur in a text without the intention of the author to cite a source.

You proved Autobib wrong :smile:. I am going to fix this.

**Comment by renerocksai** [comment]
Done. Autobib will probably take a little longer as it now has to search for both @citekey and #citekey variations. I am hesitant to limit the search to only one of them depending on the `citations-mmd-style` setting. Your bibfile is **huge**. With my super small one "ZK: Autobib" is always an instant operation. Please tell me if it is still bearable. Caching bibfile entries would probably make sense in your case.
