### ISSUE TITLE
Auto-Bib: Accidental references

### ISSUE THREAD

**Issue by doctornerdis** [renerocksai/sublime_zk#48]
I noticed another bug in the Auto-Bib function. 

![screen shot 2018-02-21 at 1 07 26 pm](https://user-images.githubusercontent.com/16094430/36505390-317abd4c-1708-11e8-86da-502db589af13.png)

In the above example, Auto-Bib is picking up the `#latin_america` tag as `#latin_`. It's then finding that same cite key by coincidence in my bib file, and generating a citation. 

Is there a way to exclude tags when Auto-Bib is parsing the file? That way, tags won't accidentally get mixed up with cite keys.

Apologies for submitting so many issues recently. If you need a break, please let me know!

**Comment by renerocksai** [comment]
Mmmm. That needs to be fixed, no doubt about that. Don't worry about submitting issues. Improvements made to sublime_zk because of your issues are benefitting all users. So they are really valuable contributions!

Your setup (large bibfile and large Zettelkasten) is a great opportunity to iron out such little bugs, short-cuts taken during implementation, and false assumptions.

There are several ways to fix this:

* Taking the whole word into account when matching cite keys. That means expecting a word separation ("stop") character at the end of the cite key (end of line, whitespace, comma, semi-colon, etc.) and ignoring the match if there is no such stop character. There is potential for error in this approach. BibDesk, for instance, defines the following characters as illegal in cite keys: `@',\#}{~%" ` according to the [BibDesk Help](https://bibdesk.sourceforge.io/manual/BibDeskHelp_2.html). That means that semi-colons, for instance, are allowed within cite-keys and must not be treated as a stop characters in the search. If you happen to have `#tag1;#tag2` in your text, and also `#tag1;` as cite-key, that would lead to an erroneous Auto-Bib entry. The next question is, should something similar also be checked for at the beginning of a cite-key? No, the `@` and `#` should be clear enough. But what about `first.last@cite-key.com`? OK, that's a bit far-fetched. 
* In addition to the above, I just realized that the whole stop character business only needs to be done when searching for `#cite-key` and not when searching for `@cite-key` (assumption). While this still does not address the `name@cite-key.com` issue, `@cite-key` will never match `#cite-key` or any `#cite-key-xyz`. The whole issue only arises when we search for `#cite-keys` in a text that contains `#hash-tags`. It should, if ever, only affect Multimarkdown users and not pandoc users. Which brings me to the next point:
* We should really honour that `citations-mmd-style` setting. If Multimarkdown is requested then it is reasonable to expect no `@cite-keys` but `[#cite-keys]`.
* Knowing that only `#cite-key` formatted cite-keys and `#hash-tags` can clash, and that `#cite-keys` are only used in Multimarkdown, it is worth also noting the Multimarkdown [syntax](http://fletcher.github.io/MultiMarkdown-5/citations.html). There we can see, that `#cite-keys` must always be enclosed by square brackets `[#cite-key]` and may have a trailing `;` (for LaTeX use: to generate `\citet` instead of `\citep`). So: no fancy "stop character" business to deal with 😓 

Conclusion:

* Instead of searching for all occurences of `@cite-key` and `#cite-key` we are going to search for all occurences of `@cite-key` and `[#cite-key` (no trailing `]` to allow for extra`;`, simplified). Maybe I'll regexp it `\[#citekey[;]?\]` though, to be precise.

Remaining issues I can think of:

* E-Mails with host names that match a cite-key
* Overlapping cite-keys like `@mr_x` and `@mr_x_2`, for instance. To eliminate this issue, it's back to stop characters again. I can also check / play with pandoc to see how it behaves in that case and what it treats as stop characters, and just mimic that behaviour.

**Comment by renerocksai** [comment]
I have just pushed a fix:

> * Instead of searching for all occurences of `@cite-key` and `#cite-key` we are going to search for all occurences of `@cite-key` and `[#cite-key`.

That should remedy your problem at hand.

Still on the back of my mind:

> * Overlapping cite-keys like @mr_x and @mr_x_2, for instance. To eliminate this issue, it's back to stop characters again. I can also check / play with pandoc to see how it behaves in that case and what it treats as stop characters, and just mimic that behaviour.

**Comment by doctornerdis** [comment]
Yup, that fixes it! 

My regex and python kung-fu are not up to the questions you're asking, but one resource might be [BibTex Parser](https://github.com/sciunto-org/python-bibtexparser). They seem to have dealt with some of these issues already. Also, I think it creates a dictionary that you could work with with auto-generating the citations.
