### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by macosxguru** [renerocksai/sublime_zk#70]
On the latest version of Sublime Text 3. I am getting this error message:

![screen shot](https://user-images.githubusercontent.com/1103821/38463934-765a9070-3ab9-11e8-80f6-5f0e6b19ac9b.png)
Can you tell me how to get rid of it?

macosxguru

**Comment by renerocksai** [comment]
Hi, please see #67. Apparently this is something `Makrdown Extended` users experience with the latest version of SublimeText, too. Disabling `Markdown Extended` or `CSS3` (and maybe `HTML5`) seems to help.

**Comment by renerocksai** [comment]
Latest ST3 just chokes on a simple `with_prototype: text.html.markdown` even with an otherwise empty syntax. The only way I could fix this was by incorporating the entire syntax of [MarkdownExtended](https://github.com/jonschlinkert/sublime-markdown-extended) and hiding the ZK stuff in the inline LaTeX section. I am glad I have a sublimeless option, anyway.
