### ISSUE TITLE
Small bugs in zk-mode

### ISSUE THREAD

**Issue by subgitlab** [renerocksai/sublime_zk#71]
#### Linux/debian-stretch. Sublime-text-3. 
This morning I download and replace sublime_zk in .config/sublime-text-3/Packages and try to load Zettelkasten Mode. 

I See that main windows divide on 
![screenshot_2018-04-10_19-24-51](https://user-images.githubusercontent.com/38258950/38573016-1677d67a-3cf5-11e8-96e4-bbefe6b86116.png)

#### It asks for create files and create:

untitled.sublime-project
.saved_searches.zks
.search_results.zkr

After I got messages which repeats themselves:
 
Error loading colour scheme Packages/sublime_zk/zk-mode/sublime_zk_results.tmTheme: Unable to open Packages/sublime_zk/zk-mode/sublime_zk_results.tmTheme

Error loading syntax file "Packages/sublime_zk/zk-mode/sublime_zk_search.sublime-syntax": Unable to read Packages/sublime_zk/zk-mode/sublime_zk_search.sublime-syntax

Error loading colour scheme Packages/sublime_zk/zk-mode/sublime_zk_search.tmTheme: Unable to open Packages/sublime_zk/zk-mode/sublime_zk_search.tmTheme

## I can "ctrl shift alt f" to search for words in files which is the best thing.

> ### *Thanks for your knowledge and sharing* :sunny: 

Sadyn

**Comment by renerocksai** [comment]
Hi Sadyn,

Sorry I get back so late. I am travelling and don't have much time.

Those `.thTheme` and syntax files are in the repository. So they must be in your package, too, when you downloaded it.

I am using the package on an old Ubuntu 16.04 Machine without problems.

It is, however, possible, that when you downloaded the ZIP file, your package is in the directory `sublime_zk-master` instead of `sublime_zk`. In that case the path `Packages/sublime_zk/zk-mode` doesn't exist.

Can you check whether that path exists?

If not: rename your downloaded sublime_zk folder to `sublime_zk` and it will work.

**Comment by subgitlab** [comment]
# Thanks Rene. 
### Issue Closed. :heart_decoration: 

Sadyn
