### ISSUE TITLE
First line syntax highlighting not working

### ISSUE THREAD

**Issue by heychad** [renerocksai/sublime_zk#75]
Hi there,
Fantastic work, Rene! I have just updated to the latest build and now for some reason the first line of my Zettels are not getting highlighted orange, like a # title should. If I hit enter and have the text start on the second line it is highlighted correctly. See these two screenshots:

https://www.dropbox.com/s/m29zvl8cplwv97t/Screenshot%202018-04-26%2009.36.17.png?dl=0

https://www.dropbox.com/s/vqckfjgqv9wzov6/Screenshot%202018-04-26%2010.01.02.png?dl=0

**Comment by renerocksai** [comment]
Yeah, I introduced that by enabling YAML syntax. Will try to get it fixed... 😀

**Comment by achamess** [comment]
Yeah, along those lines, I just updated ST, and when I open up, I get the following pop up message:

`Error loading syntax file "Packages/sublime_zk/sublime_zk.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by heychad** [comment]
I updated ST as well. Same errors. I knew I shouldn't have been so trigger happy on the updates!

**Comment by renerocksai** [comment]
this is the same issue that markdown extended has. i hope i can fix it by removing yaml from the syntax, with 2 benefits: 1st heading comes back, no recursion error. only drawback: no yaml styling

**Comment by renerocksai** [comment]
i am on a train with a flaky internet connection --- will try to fix this now

**Comment by renerocksai** [comment]
Latest ST3 just chokes on a simple `with_prototype: text.html.markdown` even with an otherwise empty syntax. The only way I could fix this was by incorporating the entire syntax of [MarkdownExtended](https://github.com/jonschlinkert/sublime-markdown-extended) and hiding the ZK stuff in the inline LaTeX section. I am glad I have a sublimeless option, anyway. 1st line headings are fixed now, too.
