### ISSUE TITLE
issues with monokai 

### ISSUE THREAD

**Issue by luctaesch** [renerocksai/sublime_zk#76]
issue with latest package ( f462dac  ), after upgrade on sublime 3170 ( previous was 3143, ok, with package date d ? ).
the monokai extended theme raise a recursive error, one by window . ( 3 for layout 3, one for 1 layout) the  solarized them does not. ( but does not highlight either) ..

![greenshot 2018-05-07 15 54 03](https://user-images.githubusercontent.com/70765/39705507-e8c98942-520e-11e8-9c32-809514671187.png)
![layout3](https://user-images.githubusercontent.com/70765/39705522-faa001e6-520e-11e8-8113-714db4cf0c00.png)
![monokai](https://user-images.githubusercontent.com/70765/39705603-2a812e58-520f-11e8-9999-f50a1d11183a.png)

**Comment by renerocksai** [comment]
this is actually the same as #75. markdown extended has the same unfixed issue. I will revert back the yaml....

**Comment by luctaesch** [comment]
fyi , I tried C64 . same issue. no issues with solarized. Tried also setting the type as mumtimarkdown . it raises no errors, for the 3 ( solararized, C64, monokai)

**Comment by renerocksai** [comment]
Latest ST3 just chokes on a simple `with_prototype: text.html.markdown` even with an otherwise empty syntax. The only way I could fix this was by incorporating the entire syntax of [MarkdownExtended](https://github.com/jonschlinkert/sublime-markdown-extended) and hiding the ZK stuff in the inline LaTeX section. I am glad I have a sublimeless option, anyway.
