### ISSUE TITLE
wiki link not work

### ISSUE THREAD

**Issue by khanhtran94** [renerocksai/sublime_zk#77]
" [[ " not work.  Scope in " [[ ]]" is text.html.markdown,  meta.paragraph.markdown, It is not link. when i press "ctrl enter" , it don't create new note. It create the white line below.
When i use my-wike from you. It create new note, but not link note markdown.

Sublime_ZK: Using ag!
![wiki link](https://user-images.githubusercontent.com/19677561/40265551-de744b8a-5b64-11e8-9cf2-007f0aa9200a.png)

can you help me? thank you

**Comment by khanhtran94** [comment]
Traceback (most recent call last):
  File "C:\Users\lennovo\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 1783, in on_done
    note_id, title = self.modified_files[selection].split(' ', 1)
ValueError: need more than 1 value to unpack

**Comment by renerocksai** [comment]
Hi, 

You are confusing things here, I think:

First, regarding the traceback: You have files in your archive that don't contain a note id: `da.md`, `link to 1.md`, `link.md`, `test.md`. When you press `[[`, you get a list of **all** `.md` files to choose from. You have selected a file without a note id, hence, when trying to insert a link, the plugin couldn't retrieve the note id, hence it didn't insert a link and you got the traceback. Agreed, on `[[` maybe other text files should be hidden, as an improvement of the plugin. But usually this is not a problem because all created notes already have a note id in the filename.

Second: When you press ctrl+enter on [[dad]], usually a new note gets created. You write, it doesn't create a new note. In addition, your note link `[[201805191252]]` is not underlined. This is suspicious, if you haven't disabled it (I assume you haven't disabled it).

Then you write, it **does** create a new note but you expected a link. You also mention "my-wike". I have no idea what you mean. Sorry, this is too confusing for me.

Please try to be more clear. 


Please make sure you read the first parts of the "Usage" section of the README. It shows how notes with note IDs are created (shift+enter). This is not a Wiki that works with arbitrary text files. The files must follow a carefully chosen convention (note ids). Only to these files can you place links.

When you have an understanding about note IDs, you will not create files with ctrl+n anymore.

Also I can see that you have a project with multiple folders. I recommend you follow the README and create a new project from scratch. Just create a new sublimetext window and press shift+enter. That should do the trick
