### ISSUE TITLE
all tags not found

### ISSUE THREAD

**Issue by danieltomasz** [renerocksai/sublime_zk#90]
I installed sublime_zk using sumblime3 and I am starting using it on Linux Ubuntu 18.04.
Anyway when I am trying to show all tags or search them I am getting
```
cmd: ag --nocolor --nofilename --nonumbers --only-matching --silent -G .*\.md (?<=\s|^)(?<!`)(\#+([^\#\s.,\/!$%\^&\*;{}\[\]'\"=`~()<>”\\]|:[a-zA-Z0-9])+) /home/daniel/Publiczny/zk_notes
sublime_zk: search unsuccessful:
```

This is an example of my note header
```
# poster_presentation
tags =  #academia


# introduction

```

**Comment by sims1253** [comment]
@danieltomasz If you alt-doubleclick or ctrl-enter with your cursor on the tag, does the note show up in the search result window?

**Comment by danieltomasz** [comment]
Yes, thanks, the problem was with the wrong path of the notes. Issue solved!

**Comment by sims1253** [comment]
@danieltomasz I was asking because I have a problem where when doing the ctrl-enter on a tag, all notes show up, but using the advanced search, not all of them show up.
Figured you might have the same problem as me but doesn't sound like it. How did you solve yours?

**EDIT**
I found my problem. I had two notes with the same id (created within the same minute) so only one of them showed up when searching.
